development:
  adapter: postgresql
  encoding: unicode
  database: jibe_dev
  pool: 5
  username: admin
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: jibe_test
  pool: 5
  username: admin
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: jibe_prod
  pool: 5
  username: admin
  password:
