development:
  adapter: postgresql
  encoding: unicode
  database: jibe_dev
  pool: 5
  username: admin

test:
  adapter: postgresql
  encoding: unicode
  database: jibe_test
  pool: 5
  username: admin

production:
  adapter: postgresql
  encoding: unicode
  database: jibe_prod
  pool: 5
  username: admin
